---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ebs-csi-driver
spec:
  releaseName: ebs-csi-driver
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/aws-ebs-csi-driver
      chart: aws-ebs-csi-driver
      version: 2.26.1
      sourceRef:
        kind: HelmRepository
        name: ebs-csi-driver
        namespace: kube-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    controller:
      region: eu-west-1
      k8sTagClusterId: "test"
      serviceAccount:
        name: ebs-csi-controller-sa
        # annotations:
        #   eks.amazonaws.com/role-arn: "arn:aws:iam::AWS_ACCOUNT_ID:role/IAM_ROLE_NAME"
    node:
      tolerateAllTaints: true
