apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ebs-csi-driver
  namespace: kube-system
spec:
  interval: 30m
  url: https://kubernetes-sigs.github.io/aws-ebs-csi-driver