---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: calico
  namespace: tigera-operator
spec:
  releaseName: calico
  chart:
    spec:
      chart: tigera-operator
      version: v3.24.5
      sourceRef:
        kind: HelmRepository
        name: projectcalico
        namespace: flux-system
  interval: 30m0s
  install:
    remediation:
      retries: 3
---
