---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: kube-system
spec:
  releaseName: external-secrets
  chart:
    spec:
      chart: external-secrets
      version: 0.9.16
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    fullnameOverride: external-secrets-operator
    leaderElect: true
    replicaCount: 3
    # serviceAccount:
      # annotations:
      #   eks.amazonaws.com/role-arn: arn:aws:iam::AWS_ACCOUNT_ID:role/IAM_ROLE_NAME
