---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: kube-system
spec:
  releaseName: external-secrets
  chart:
    spec:
      # renovate: registryUrl=https://charts.external-secrets.io
      chart: external-secrets
      version: 0.5.3
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: kube-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    fullnameOverride: external-secrets-operator
    # serviceAccount:
      # annotations:
      #   eks.amazonaws.com/role-arn: arn:aws:iam::AWS_ACCOUNT_ID:role/IAM_ROLE_NAME