---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reloader
  namespace: kube-system
spec:
  releaseName: reloader
  chart:
    spec:
      chart: reloader
      version: v0.0.113
      sourceRef:
        kind: HelmRepository
        name: reloader
        namespace: kube-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    reloader:
      watchGlobally: true
      deployment:
        replicas: 1
    