---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: load-balancer-controller
  namespace: kube-system
spec:
  releaseName: load-balancer-controller
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: 1.4.2
      sourceRef:
        kind: HelmRepository
        name: load-balancer-controller
        namespace: kube-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    fullnameOverride: load-balancer-controller
    clusterName: "test"
    replicaCount: 3
    serviceAccount:
      create: true
      annotations: {}
        # eks.amazonaws.com/role-arn: arn:aws:iam::AWS_ACCOUNT_ID:role/IAM_ROLE_NAME
    