---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: kube-system
spec:
  releaseName: kube-state-metrics
  chart:
    spec:
      chart: kube-state-metrics
      version: 4.7.0
      sourceRef:
        kind: HelmRepository
        name: kube-state-metrics
        namespace: kube-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    replicas: 3
    