apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kube-state-metrics
  namespace: kube-system
spec:
  interval: 30m
  url: https://prometheus-community.github.io/helm-charts
