---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kubecost
  namespace: kubecost
spec:
  releaseName: kubecost
  chart:
    spec:
      chart: cost-analyzer
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: kubecost
        namespace: kubecost
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    kubecostMetrics:
      exporter:
        enabled: true
---
