---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubecost
  namespace: kubecost
spec:
  releaseName: kubecost
  chart:
    spec:
      chart: cost-analyzer
      version: 1.93.2
      sourceRef:
        kind: HelmRepository
        name: kubecost
        namespace: kubecost
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    prometheus:
      kube-state-metrics:
        disabled: true
      nodeExporter:
        enabled: false
    networkCosts:
      enabled: false
    kubecostMetrics:
      exporter:
        enabled: true
---
