---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: karpenter
  namespace: kube-system
spec:
  releaseName: karpenter
  chart:
    spec:
      # renovate: registryUrl=https://charts.karpenter.sh/
      chart: karpenter
      version: 0.10.1
      sourceRef:
        kind: HelmRepository
        name: karpenter
        namespace: kube-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
    replicas: 2
    serviceAccount:
      name: karpenter
    logLevel: debug
    # clusterName: "YOUR_CLUSTER_NAME"
    # clusterEndpoint: "YOUR_CLUSTER_ENDPOINT"
    # serviceAccount:
    #   annotations:
    #     eks.amazonaws.com/role-arn: "arn:aws:iam::AWS_ACCOUNT_ID:role/IAM_ROLE_NAME"