---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: karpenter
  namespace: karpenter
spec:
  releaseName: karpenter
  chart:
    spec:
      chart: karpenter
      version: v0.19.3
      sourceRef:
        kind: HelmRepository
        name: karpenter
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    controller:
      image: public.ecr.aws/karpenter/controller:v0.19.3
    replicas: 2
    serviceAccount:
      name: karpenter
    logLevel: debug
    # clusterName: "YOUR_CLUSTER_NAME"
    # clusterEndpoint: "YOUR_CLUSTER_ENDPOINT"
    # serviceAccount:
    #   annotations:
    #     eks.amazonaws.com/role-arn: "arn:aws:iam::AWS_ACCOUNT_ID:role/IAM_ROLE_NAME"
