---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: karpenter
  namespace: karpenter
spec:
  releaseName: karpenter
  chart:
    spec:
      chart: karpenter
      version: v0.36.1
      sourceRef:
        kind: HelmRepository
        name: karpenter
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    replicas: 3
    serviceAccount:
      name: karpenter
    logLevel: debug
    controller:
      resources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 1
          memory: 1Gi
    # clusterName: "YOUR_CLUSTER_NAME"
    # serviceAccount:
    #   annotations:
    #     eks.amazonaws.com/role-arn: "arn:aws:iam::AWS_ACCOUNT_ID:role/IAM_ROLE_NAME"
