---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  releaseName: metrics-server
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/metrics-server/
      chart: metrics-server
      version: 3.8.2
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: kube-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
