---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  releaseName: external-dns
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/external-dns/
      chart: external-dns
      version: 1.9.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: kube-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    aws:
      region: eu-west-1
    sources:
      - service
      - ingress
    rbac:
      create: true
    # serviceAccount:
    #   annotations:
    #     eks.amazonaws.com/role-arn: "arn:aws:iam::AWS_ACCOUNT_ID:role/IAM_ROLE_NAME"
