---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: 1.8.0
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      tag: v1.8.0
    ingressShim:
      defaultIssuerName: letsencrypt
      defaultIssuerKind: ClusterIssuer
      defaultACMEChallengeType: dns01
      defaultACMEDNS01ChallengeProvider: route53
    installCRDs: true
    # serviceAccount:
    #   annotations:
    #     eks.amazonaws.com/role-arn: "arn:aws:iam::AWS_ACCOUNT_ID:role/IAM_ROLE_NAME"
    securityContext:
      runAsNonRoot: true
      fsGroup: 65534
      runAsUser: 65534
    prometheus:
      enabled: true
    extraArgs:
    - --dns01-recursive-nameservers=1.1.1.1:53,8.8.8.8:53