---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: seldon-core-operator
  namespace: seldon-system
spec:
  interval: 5m
  releaseName: seldon-core-operator
  chart:
    spec:
      chart: seldon-core-operator
      version: 1.13.1
      sourceRef:
        kind: HelmRepository
        name: seldon-charts
        namespace: seldon-system
  values:
    usageMetrics:
      enabled: false
    istio:
      enabled: false
