---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: seldon-charts
  namespace: seldon-system
spec:
  interval: 30m
  url: https://storage.googleapis.com/seldon-charts
